language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
os:
- linux
cache: cargo

install:
- command -v just || cargo install just
script:
- just travis-ci
